### ISSUE TITLE
Dodać metody do pobierania propertiesów do interfejsu Message

### ISSUE THREAD

**Issue by rafal-strzelbicki** [landingi/aws-bundle#12]
https://github.com/landingi/aws-bundle/blob/96fc3fd34a920c2c79e8f4e1380944e12de87a00/src/Queue/Message.php#L6

- Z doświadczenia wiem, że nie wysyłamy nigdy pustych message'y (bez propertiesów) więc brakuje mi metod getProperty oraz getRequiredProperty tak jak jest w worker-queue, to nie psuje abstrakcji.
- imo dobrze, że nie ma metody getAction bo to szczegół implementacyjny AWS SQS 👌

**Comment by Ferror** [comment]
`getProperty` spoko, ale nie definiowałbym czegoś takiego jak `getRequiredProperty` - to już jest stricte logika w worker-queue, że mamy wgl parametry, których może nie być to jest żart dla queue XD

**Comment by Ferror** [comment]
Też jak teraz o tym myślę, to jak zdefiniuje getProperty to bede musiał definiować co on zwraca, a tam mogą byc array, string ,int...
